<?xml version="1.0"?>
<package format="3">
  <name>ros_study_description</name>
  <version>0.1.0</version>
  <description>Canonical ROS 2 description package for the zero_ros slides.</description>
  <maintainer email="yusaku_nakajima@ap.eng.osaka-u.ac.jp">Yusaku Nakajima</maintainer>
  <license>CC-BY-NC-ND-4.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>joint_state_publisher_gui</depend>
  <depend>gz_ros2_control</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>robot_state_publisher</depend>
  <depend>rviz2</depend>
  <depend>ur_description</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
