<?xml version="1.0"?>
<package format="3">
  <name>ros_study_bringup</name>
  <version>0.1.0</version>
  <description>Bringup launch files and controller configuration for the zero_ros slides.</description>
  <maintainer email="yusaku_nakajima@ap.eng.osaka-u.ac.jp">Yusaku Nakajima</maintainer>
  <license>CC-BY-NC-ND-4.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>controller_manager</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>joint_trajectory_controller</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>robot_state_publisher</depend>
  <depend>ros2_control</depend>
  <depend>ros2_controllers</depend>
  <depend>ros_gz_bridge</depend>
  <depend>ros_gz_sim</depend>
  <depend>rviz2</depend>
  <depend>ur_client_library</depend>
  <depend>ur_moveit_config</depend>
  <depend>ur_robot_driver</depend>
  <depend>xacro</depend>
  <depend>ros_study_description</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
